---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-data
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grimmory-books
  annotations:
    helm.sh/resource-policy: keep
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
