apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: headscale
  namespace: headscale
spec:
  interval: 24h
  url: oci://ghcr.io/gabe565/charts/headscale
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: "0.16.0"
