---
apiVersion: v1
kind: Namespace
metadata:
  name: coroot
  labels:
    toolkit.fluxcd.io/tenant: sre-team
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: coroot
  namespace: coroot
spec:
  interval: 12h
  url: https://coroot.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coroot-operator
  namespace: coroot
spec:
  interval: 12h
  chart:
    spec:
      chart: coroot-operator
      version: "0.9.x"
      sourceRef:
        kind: HelmRepository
        name: coroot
  install:
    strategy:
      name: RetryOnFailure
    crds: CreateReplace
  upgrade:
    strategy:
      name: RetryOnFailure
    crds: CreateReplace
