apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - longhorn.yaml
  - gateway-api
  - kgateway-crds.yaml
  - kgateway.yaml
  - cert-manager.yaml
  - coroot-operator.yaml
  - cert-manager-lego-webhook.yaml